
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'SLR'

_lr_signature = "\xada|%o\x17\xad\x85V'\xa6y6\x8b\xdb\xb6"

_lr_action_items = {'int':([0,],[2,]),',':([6,],[7,]),'float':([0,],[3,]),'id':([2,3,4,7,],[-2,-3,6,6,]),'$end':([1,5,6,8,],[0,-1,-5,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'DECL':([0,],[1,]),'VAR_LIST':([4,7,],[5,8,]),'TYPE':([0,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('DECL',2,'p_DECL','./ejemplo2_yacc.py',24),
  ('TYPE',1,'p_TYPE','./ejemplo2_yacc.py',28),
  ('TYPE',1,'p_TYPE','./ejemplo2_yacc.py',29),
  ('VAR_LIST',3,'p_VAR_LIST','./ejemplo2_yacc.py',33),
  ('VAR_LIST',1,'p_VAR_LIST','./ejemplo2_yacc.py',34),
]
